version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: nuget restore
build_script:
- cmd: >-
    nuget restore

    dotnet build -p:AssemblyVersion=%%APPVEYOR_BUILD_VERSION%% -c:Release

    dotnet publish -p:PublishProfile=Win10Appveyor.pubxml -p:AssemblyVersion=%%APPVEYOR_BUILD_VERSION%% -c:Release --output %appveyor_build_folder%\dist
artifacts:
- path: ComPortCapture.exe
  name: WinExe