version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: nuget restore
build_script:
- cmd: >-
    dotnet publish -r win-x64 -c Release -p:AssemblyVersion=%APPVEYOR_BUILD_VERSION% --force --output %APPVEYOR_BUILD_FOLDER%
artifacts:
- path: ComPortCapture.exe
  name: WinExe