version: 1.0.{build}
branches:
  only:
  - main
skip_tags: true
image: Visual Studio 2019
install:
- cmd: git submodule update --init --recursive
before_build:
- cmd: nuget restore
build_script:
- cmd: >-
    dotnet publish -r win-x64 -c Release -p:AssemblyVersion=%APPVEYOR_BUILD_VERSION% --force --output %APPVEYOR_BUILD_FOLDER%
artifacts:
- path: ComPortCapture.exe
  name: WinExe
deploy:
  release: ComPortCapture-v$(appveyor_build_version)
  description: 'ComPortCapture v$(appveyor_build_version)'
  provider: GitHub
  auth_token:
    secure: W5+n+IkGZOEHXp3kx9PNIdhheM/3yL2CnU72QACC25lMLT+edLb+69id/w+ZAJ0y
  artifact: ComPortCapture.exe
  draft: false
  prerelease: false
  on:
    branch: main